image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent


database:
  username: keycloak-uat
  password: uat123
  name: keycloak-uat


resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

storage:
  size: 4Gi
  storageClass: local-path

service:
  port: 5432
